### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by velijv**
# Proposed Changes

## Update logo

- [ ] Previous logo #125 (by me) was a quick hack. 
- [x] This one takes into consideration dark and light themes by using the gray exactly in the middle. 
- [x] Modified the logo to be more uniform.

example

## Related Issues

- #141 
- - I used pull request comments as a discussion, apologies! 
- -  *Hope this PR is better formatted 🙇*

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
In the mean time, we have updated the Supervisor to support dark mode icons, so we can use the previous PR now.

**Comment by velijv** [comment]
✅ Added light and dark mode icons instead of the gray.

**Comment by velijv** [comment]
@frenck what do you think? Because otherwise:

> This pull request has been automatically marked as stale because of that and will be closed if no further activity occurs within 7 days. Thank you for your contributions.

**Comment by frenck** [comment]
Meh, ok, so the supervisor didn't went through with the dark logo support change :(

**Pull request closed without merging**
