### PR TITLE
add dark icons

### PR DESCRIPTION
**Pull request by velijv**
# Proposed Changes

> add dark icons because black on black is stylish but illegible. 🌓 #140 

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by frenck** [comment]
How did the testing go?

**Comment by frenck** [comment]
> I havent figured out how to add label to pull request

That is not something you have to worry about. That is a categorization task for me.

Nevertheless, the question remains: How did the testing go?

**Comment by velijv** [comment]
Before: 👎
image

After: 👍
image

**Comment by frenck** [comment]
It's interesting, as the Supervisor API doesn't support it...
Nor does it support hDPI images.

**Comment by velijv** [comment]
Ah okay, didn't know that. Assumed it worked the same way as official icons. Based them on my [original icons](https://github.com/hassio-addons/addon-aircast/pull/125). 
Should I create a colored version instead, that can be used in both light and dark modes?

Since it is a butchered mashup of both, it doesn't have to follow any guides, but both seem to use monochrome:
- https://www.google.com/search?q=google+cast+logo+site%3Agoogle.com
- https://www.google.com/search?q=airplay+logo+site%3Aapple.com

This is exactly between #000 and #fff
Group 140

**Comment by velijv** [comment]
Since Cast https://github.com/home-assistant/brands/pull/3067 updated its logo, maybe it's time to update Aircast as well?

[Sorry Google](https://developers.google.com/cast/docs/ux_guidelines#chromecast_badge), [Sorry Apple](https://developer.apple.com/design/human-interface-guidelines/technologies/airplay/icons/)
Frame 1

**Comment by frenck** [comment]
I don't see how that is related to this PR.

Anyways, this PR cannot work, as the Supervisor has no support for this. The hDPI images also don't work.

Closing this PR for now for that reason.

**Pull request closed without merging**
